# Generated by Django 4.0.4 on 2022-11-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('last_task', models.CharField(blank=True, max_length=32)),
                ('last_data', models.CharField(blank=True, max_length=64)),
                ('board_number', models.IntegerField(default=0)),
                ('set_hands', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('use_set_hands', models.BooleanField(default=False)),
                ('display_hand_type', models.BooleanField(default=False)),
                ('own_bid', models.CharField(blank=True, max_length=32)),
                ('suggested_bid', models.CharField(blank=True, max_length=32)),
                ('board_pbn', models.CharField(blank=True, default='', max_length=512, null=True)),
                ('board', models.TextField(blank=True)),
                ('archive', models.TextField(blank=True)),
            ],
        ),
    ]
