# Generated by Django 4.1.4 on 2023-03-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_bfguser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BfgUser',
        ),
        migrations.AlterField(
            model_name='room',
            name='set_hands',
            field=models.CharField(blank=True, default='[]', max_length=512),
        ),
    ]
