# Generated by Django 4.1.4 on 2023-03-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_delete_bfguser_alter_room_set_hands'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=180)),
                ('use_set_hands', models.BooleanField(default=False)),
                ('set_hands', models.CharField(blank=True, default='[]', max_length=512)),
                ('display_hand_type', models.CharField(blank=True, default='{"solo": true, "duo": true}', max_length=32)),
            ],
        ),
    ]
