# Generated by Django 4.1.4 on 2023-03-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='room',
            name='display_hand_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='room',
            name='set_hands',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='use_set_hands',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
