# Generated by Django 4.1.4 on 2023-03-10 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_alter_room_display_hand_type_alter_room_set_hands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='display_hand_type',
            field=models.CharField(blank=True, default='{"solo": false, "duo": false}', max_length=32),
        ),
        migrations.AlterField(
            model_name='room',
            name='set_hands',
            field=models.CharField(blank=True, default='{"solo": [], "duo": []}', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='use_set_hands',
            field=models.CharField(blank=True, default='{"solo": false, "duo": false}', max_length=32),
        ),
    ]
