# Generated by Django 4.1.4 on 2023-03-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_room_display_hand_type_alter_room_set_hands_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='display_hand_type',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='set_hands',
            field=models.CharField(blank=True, default='[]', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='use_set_hands',
            field=models.BooleanField(default=False),
        ),
    ]
