# Generated by Django 4.1.4 on 2023-03-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_alter_room_display_hand_type_alter_room_set_hands_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='saved_boards',
            field=models.TextField(blank=True),
        ),
    ]
