# Generated by Django 4.1.4 on 2023-08-26 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_alter_room_saved_boards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='saved_boards',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
