# Generated by Django 5.2.7 on 2025-12-22 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_alter_room_saved_boards'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='saved_pbn',
            field=models.CharField(blank=True, default='', max_length=512, null=True),
        ),
    ]
