# Generated by Django 5.2.7 on 2026-01-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_room_saved_pbn'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('logged_in', models.BooleanField(default=False)),
                ('last_activity', models.DateField(null=True)),
            ],
        ),
    ]
