# Generated by Django 5.2.7 on 2026-01-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0013_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(null=True),
        ),
    ]
